"""created upload tables

Revision ID: 569b97dce6de
Revises: 978bfabcbb09
Create Date: 2026-04-21 22:37:34.530968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569b97dce6de'
down_revision = '978bfabcbb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
