"""temperory photo tables

Revision ID: 67702c664b0e
Revises: 569b97dce6de
Create Date: 2026-04-21 22:53:20.672715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67702c664b0e'
down_revision = '569b97dce6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('r2_upload_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('upload_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.upload_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_parts')
    op.drop_table('uploads')
    # ### end Alembic commands ###
