"""user table changes

Revision ID: 978bfabcbb09
Revises: 4d16eae1da37
Create Date: 2026-04-15 21:18:12.946231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978bfabcbb09'
down_revision = '4d16eae1da37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
