"""Add ondelete CASCADE for event relationships

Revision ID: f3b01e62fcee
Revises: 67702c664b0e
Create Date: 2026-04-27 12:52:01.272043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b01e62fcee'
down_revision = '67702c664b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('photos_event_id_fkey'), 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('upload_parts_upload_id_fkey'), 'upload_parts', type_='foreignkey')
    op.create_foreign_key(None, 'upload_parts', 'uploads', ['upload_id'], ['upload_id'], ondelete='CASCADE')
    op.add_column('uploads', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'event_id')
    op.drop_constraint(None, 'upload_parts', type_='foreignkey')
    op.create_foreign_key(op.f('upload_parts_upload_id_fkey'), 'upload_parts', 'uploads', ['upload_id'], ['upload_id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key(op.f('photos_event_id_fkey'), 'photos', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
